model_list:
  - model_name: mistralai/Mixtral-8x7B-Instruct-v0.1
    litellm_params:
      model: anyscale/mistralai/Mixtral-8x7B-Instruct-v0.1
      api_base: https://api.endpoints.anyscale.com/v1
      api_version: "2023-05-15"
      api_key: os.environ/ANYSCALE
  - model_name: codellama/CodeLlama-34b-Instruct-hf
    litellm_params:
      model: anyscale/codellama/CodeLlama-34b-Instruct-hf
      api_base: https://api.endpoints.anyscale.com/v1
      api_key: os.environ/ANYSCALE
  - model_name: mistralai/Mixtral-8x22B-Instruct-v0.1
    litellm_params:
      model: anyscale/mistralai/Mixtral-8x22B-Instruct-v0.1
      api_base: https://api.endpoints.anyscale.com/v1
      api_key: os.environ/ANYSCALE
  - model_name: meta-llama/Meta-Llama-3-70B-Instruct
    litellm_params:
      model: anyscale/meta-llama/Meta-Llama-3-70B-Instruct
      api_base: https://api.endpoints.anyscale.com/v1
      api_key: os.environ/ANYSCALE
  - model_name: codellama/CodeLlama-70b-Instruct-hf
    litellm_params:
      model: anyscale/codellama/CodeLlama-70b-Instruct-hf
      api_base: https://api.endpoints.anyscale.com/v1
      api_key: os.environ/ANYSCALE
